Add server skeleton
denbykov/upVibe-server pull request #12
Opened 2023-07-22 13:17 UTC by VolodymyrFihurniak

2023-07-22 18:14 UTC, denbykov requested changes

2023-07-22 18:14 UTC, denbykov commented on server/src/business/authWorker.ts
> +    const token = await this.db.findTokenByRefreshToken(refreshTokenId);
Rename it to the "findAccessTokenByRefreshTokenId"

2023-07-22 18:14 UTC, denbykov commented on server/src/business/authWorker.ts
> +    };
I think you can create a separate function that will create a token, update database and return it

2023-07-22 18:14 UTC, denbykov commented on server/src/business/authWorker.ts
> +        this.db.closeConnection();
Why are you closing a db connection here?

2023-07-22 18:14 UTC, denbykov commented on server/src/controllers/auth.controller.ts
> +  public refreshToken = async (req: Request, res: Response) => {
I believe that you are creating an access token here, so name it accessToken

2023-07-22 18:14 UTC, denbykov commented on server/src/controllers/base.controller.ts
> +  protected _config: Config;
Why do you have an underscore in the name of this property here?

2023-07-22 18:14 UTC, denbykov commented on server/src/middlewares/auth0Middleware.ts
> +        message: "Token invalid",
"Token is invalid" would be better

2023-07-22 18:14 UTC, denbykov commented on server/src/middlewares/auth0Middleware.ts
> +        message: "Token invalid",
"Token is invalid" would be better

2023-07-22 18:14 UTC, denbykov commented on server/src/middlewares/index.ts
> +import { requestLogger } from "./loggerRequest";
Weird naming

2023-07-22 18:14 UTC, denbykov commented on server/src/server.ts
> +  serverLogger.error("APP_PORT and APP_HOST are not defined");
These variables have different names now

2023-07-22 18:14 UTC, denbykov commented on server/src/data/Database.ts
> +  public client: Promise<pg.PoolClient>;
PoolClient is a Pool manager or an object being managed by the pool? The second seems to be true, and if that is the case, then it has to be rewritten

2023-07-23 12:21 UTC, VolodymyrFihurniak commented on server/config/log4j.properties
> +        "server": { "appenders": ["out", "app"], "level": "debug", "enableCallStack": true }
Fixed

2023-07-23 12:47 UTC, denbykov approved these changes

2023-07-23 12:49 UTC, merged