Uvs 117: Implement file deletion API
denbykov/upVibe-server pull request #162
Opened 2024-06-30 18:48 UTC by VolodymyrFihurniak

2024-07-04 19:20 UTC, denbykov requested changes

2024-07-04 19:20 UTC, denbykov commented on server/sql/deleteUserFile.sql
> +  user_id = $1
Why would you need a user_id here if you already have an id?

2024-07-04 19:20 UTC, denbykov commented on server/src/business/fileWorker.ts
> +      existFile!.id
This code does not make any sense

2024-07-04 19:20 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    const existFile = await this.db.getUserFile(user.id, fileId);
Rename to existsingFile

2024-07-04 19:20 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    const existSync = await this.db.getSyncrhonizationRecordsByDevice(
Rename to existsingSync

2024-07-04 19:20 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    const existPlaylistFile = await this.playlistDb.getUserPlaylistFile(
You have to fetch all the records here, not a single one.

2024-07-04 19:20 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    });
The rest is not able to make sense as AC 1.3 is compromised

2024-07-05 10:19 UTC, VolodymyrFihurniak commented on server/src/business/fileWorker.ts
> +      existFile!.id
AC 1.3

2024-07-06 09:54 UTC, denbykov requested changes

2024-07-06 09:54 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    await this.db.deleteUserFile(existsingFile!.id);
It should be deleted only for current user

2024-07-06 09:54 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    });
This loop does not work. Instead you should delete only one file by fileId

2024-07-06 13:43 UTC, denbykov approved these changes, later dismissed

2024-07-06 13:43 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    await this.tagDb.deleteTagMapping(user.id, fileId);
Should be deleted for all users

2024-07-06 13:43 UTC, denbykov commented on server/src/business/fileWorker.ts
> +      await fs.unlink(file!.path);
Unlink should be moved to the data layer

2024-07-06 13:43 UTC, denbykov commented on server/src/business/fileWorker.ts
> +    await this.tagDb.deleteTag(fileId);
You need to delete images from the filesystem

2024-07-07 09:30 UTC, denbykov approved these changes

2024-07-07 09:33 UTC, merged