Uvs 49: Implement tag mappings API
denbykov/upVibe-server pull request #85
Opened 2024-04-07 15:56 UTC by VolodymyrFihurniak

2024-04-07 16:56 UTC, denbykov requested changes

2024-04-07 16:56 UTC, denbykov commented on server/src/dto/taggedFileDTO.ts
> +class FileMappingDTO {
I believe it should be named TagMappingDTO

2024-04-07 16:56 UTC, denbykov commented on server/src/dto/taggedFileDTO.ts
>  class TaggedFileDTO {
Do not change this DTO

2024-04-07 16:56 UTC, denbykov commented on server/src/dto/taggedFileDTO.ts
> +class FileMappingDTO {
And moved to the separate file

2024-04-07 16:56 UTC, denbykov commented on server/src/entities/file.ts
> +class FileMapping {
Rename to TagMapping and move to the separate file

2024-04-07 16:56 UTC, denbykov commented on server/src/entities/file.ts
> +class File {
Do not change File Entity. Create another one, that will include both file and mapping.

2024-04-12 17:13 UTC, VolodymyrFihurniak commented on server/src/controllers/tagMappingController.ts
> +      if (Object.keys(request.body).length == 0) {
This code can be written as follows:
```
const requiredFields = ['title', 'artist', 'album', 'picture', 'year', 'trackNumber'];

for (let field of requiredFields) {
  if (!request.body[field]) {
    return response.status(400).json({ error: `${field.charAt(0).toUpperCase() + field.slice(1)} is required` });
  }
}
```

2024-04-12 21:14 UTC, VolodymyrFihurniak commented
Use method toString() conversion from number to string type

2024-04-13 11:29 UTC, denbykov approved these changes

2024-04-13 11:29 UTC, merged